-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE user_order (
	id serial PRIMARY KEY NOT NULL,
	order_number varchar(300) NULL,
	tracking_number varchar(300) NULL,
	status varchar(300) NULL,
	order_date timestamp NOT NULL,
	shipping_address varchar(300) NULL,
	payment_method varchar(300) NULL,
	card_number varchar(300) NULL,
	delivery_method varchar(300) NULL,
	delivery_fee int2 NOT NULL,
	discount int2 NULL,
	total_amount int2 NOT NULL,
	products jsonb NOT NULL,
	user_id int4 NOT NULL,
  CONSTRAINT fk_user
    FOREIGN KEY(user_id)
      REFERENCES users(id)
);

CREATE TABLE users (
	id serial PRIMARY KEY NOT NULL,
	"name" varchar(300) NULL,
	email varchar(300) NULL,
	"password" varchar(500) NULL,
	created_on timestamp NULL,
	last_login timestamp NULL,
	"admin" bool NULL
);

CREATE TABLE products(
	id serial PRIMARY KEY NOT NULL,
	"name" varchar(300) NOT NULL,
	category varchar(300) NOT NULL,
	subtitle varchar(300) NOT NULL,
	price INTEGER NOT NULL,
	discount INTEGER,
	"size" varchar(10) NOT NULL,
	color varchar(100) NOT NULL,
	description varchar(1000) NOT NULL,
	rating int2 NOT NULL,
	reviews int2 NOT NULL,
	stock int2 NOT NULL,
	image_url varchar(1000) NOT NULL,
	image_detail_url _text,
	product_type varchar(1000));

CREATE TABLE user_favorite (
	id serial NOT NULL,
	product_id int2 NOT NULL,
	user_id int2 NOT NULL,
  CONSTRAINT fk_product
    FOREIGN KEY(product_id)
      REFERENCES products(id),
  CONSTRAINT fk_user
    FOREIGN KEY(user_id)
      REFERENCES users(id)
);

CREATE TABLE user_cart (
	id serial NOT NULL,
	product_id int2 NOT NULL,
	user_id int2 NOT NULL,
  amount INTEGER NOT NULL,
  CONSTRAINT fk_product
    FOREIGN KEY(product_id)
      REFERENCES products(id),
  CONSTRAINT fk_user
    FOREIGN KEY(user_id)
      REFERENCES users(id)
);

CREATE TABLE chat (
	id serial PRIMARY KEY NOT NULL,
	user_id int4 NOT NULL,
	message varchar(10000000) NULL,
	to_user int4 NOT NULL,
	message_sent timestamp NULL,
  CONSTRAINT fk_user
    FOREIGN KEY(user_id)
      REFERENCES users(id),
  CONSTRAINT fk_to_user
    FOREIGN KEY(to_user)
      REFERENCES users(id)
);